# Generated by Django 5.0.1 on 2024-03-09 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_hoteldetails',
            name='checkin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotel_hoteldetails',
            name='checkout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
