# Generated by Django 5.0.1 on 2024-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_hoteldetails_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_hoteldetails',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='hotel_hoteldetails',
            name='checkout',
        ),
    ]
