# Generated by Django 5.0.1 on 2024-04-26 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_room_details_delete_hoteldetails_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='address',
            field=models.TextField(default='aaaaaa', max_length=200),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='adults',
            field=models.IntegerField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='check_in',
            field=models.DateField(default=datetime.datetime, max_length=10),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='check_out',
            field=models.DateField(default=datetime.datetime, max_length=10),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='children',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='city',
            field=models.CharField(default='huh', max_length=10),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='country',
            field=models.CharField(default='india', max_length=10),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='email',
            field=models.EmailField(default='22@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='name',
            field=models.CharField(blank=True, default='abc', max_length=20),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='phone',
            field=models.BigIntegerField(default='9999', max_length=10),
        ),
    ]
